//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger.ConfigApp.BasicServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BasicServiceReference.BasicServiceSoap")]
    public interface BasicServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataBaseDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataBaseDataSet(string strSql, string strTableName, string strDataBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentByKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDepartmentByKey(string strName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRootDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRootDepartment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentByDeptID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDepartmentByDeptID(string DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeptCurrent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeptCurrent(string DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartmentByCodeName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDepartmentByCodeName(string deptCode, string deptName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByDept", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserByDept(string DepartmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployeeInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllEmployeeInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeByType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmployeeByType(string p_strEmployeeType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetMaxNO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ChangeEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserFunction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllUserRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserRole(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser2Role", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddUser2Role(string strUserID, string strRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelectUser2Role", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DelectUser2Role(string strUserID, string strRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserRole2Function", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserRole2Function(string strRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUserRole2Function", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteUserRole2Function(string strRoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserIDbyCardNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetUserIDbyCardNO(string p_strCardNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserByUserID(string p_strUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePrintSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SavePrintSettings(System.Data.DataSet dst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPrintSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllPrintSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrintSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPrintSettings(string modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllWorkFlow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveWorkFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveWorkFlow(System.Data.DataSet dst);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicServiceSoapChannel : Tiger.ConfigApp.BasicServiceReference.BasicServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicServiceSoapClient : System.ServiceModel.ClientBase<Tiger.ConfigApp.BasicServiceReference.BasicServiceSoap>, Tiger.ConfigApp.BasicServiceReference.BasicServiceSoap {
        
        public BasicServiceSoapClient() {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataBaseDataSet(string strSql, string strTableName, string strDataBase) {
            return base.Channel.GetDataBaseDataSet(strSql, strTableName, strDataBase);
        }
        
        public System.Data.DataSet GetAllDepartment() {
            return base.Channel.GetAllDepartment();
        }
        
        public System.Data.DataSet GetDepartmentByKey(string strName) {
            return base.Channel.GetDepartmentByKey(strName);
        }
        
        public System.Data.DataSet GetRootDepartment() {
            return base.Channel.GetRootDepartment();
        }
        
        public System.Data.DataSet GetDepartmentByDeptID(string DepartmentID) {
            return base.Channel.GetDepartmentByDeptID(DepartmentID);
        }
        
        public System.Data.DataSet GetDeptCurrent(string DepartmentID) {
            return base.Channel.GetDeptCurrent(DepartmentID);
        }
        
        public System.Data.DataSet GetDepartmentByCodeName(string deptCode, string deptName) {
            return base.Channel.GetDepartmentByCodeName(deptCode, deptName);
        }
        
        public System.Data.DataSet GetUserByDept(string DepartmentID) {
            return base.Channel.GetUserByDept(DepartmentID);
        }
        
        public System.Data.DataSet GetAllEmployeeInfo() {
            return base.Channel.GetAllEmployeeInfo();
        }
        
        public System.Data.DataSet GetEmployeeByType(string p_strEmployeeType) {
            return base.Channel.GetEmployeeByType(p_strEmployeeType);
        }
        
        public int GetMaxNO() {
            return base.Channel.GetMaxNO();
        }
        
        public void ChangeEmployee() {
            base.Channel.ChangeEmployee();
        }
        
        public System.Data.DataSet GetUserFunction() {
            return base.Channel.GetUserFunction();
        }
        
        public System.Data.DataSet GetAllUserRole() {
            return base.Channel.GetAllUserRole();
        }
        
        public System.Data.DataSet GetUserRole(string userID) {
            return base.Channel.GetUserRole(userID);
        }
        
        public int AddUser2Role(string strUserID, string strRoleID) {
            return base.Channel.AddUser2Role(strUserID, strRoleID);
        }
        
        public int DelectUser2Role(string strUserID, string strRoleID) {
            return base.Channel.DelectUser2Role(strUserID, strRoleID);
        }
        
        public System.Data.DataSet GetUserRole2Function(string strRoleID) {
            return base.Channel.GetUserRole2Function(strRoleID);
        }
        
        public int DeleteUserRole2Function(string strRoleID) {
            return base.Channel.DeleteUserRole2Function(strRoleID);
        }
        
        public string[] GetUserIDbyCardNO(string p_strCardNO) {
            return base.Channel.GetUserIDbyCardNO(p_strCardNO);
        }
        
        public System.Data.DataSet GetUserByUserID(string p_strUserID) {
            return base.Channel.GetUserByUserID(p_strUserID);
        }
        
        public void SavePrintSettings(System.Data.DataSet dst) {
            base.Channel.SavePrintSettings(dst);
        }
        
        public System.Data.DataSet GetAllPrintSettings() {
            return base.Channel.GetAllPrintSettings();
        }
        
        public System.Data.DataSet GetPrintSettings(string modelName) {
            return base.Channel.GetPrintSettings(modelName);
        }
        
        public System.Data.DataSet GetAllWorkFlow() {
            return base.Channel.GetAllWorkFlow();
        }
        
        public void SaveWorkFlow(System.Data.DataSet dst) {
            base.Channel.SaveWorkFlow(dst);
        }
    }
}
